### ISSUE TITLE
Add rss.xml for rss feeds

### ISSUE THREAD

**Issue by nirtamir2** [PuruVJ/puruvjdev2#26]
Hi,
Thank you for your open-source projects + content!
I would like to subscribe to updates via RSS.
I can hack it myself, but it's better to add an RSS feed to your site as a best practice.
I don't know sapper well enough, but it seems like you need to export `rss.xml` for rss feeders file that contain something like

```js
  const rssContent = `<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0">
<channel>
	<title>Blog // Puru Vijay</title>
	<link>https://puruvj.dev/rss.xml</link>
	<description>Read about web development, designing and programming on Puru Vijay's blog.</description>
	${posts.map(post => `
		<item>
			<title>${post.title}</title>
			<link>https://puruvj.dev/blog/${post.id}</link>
			<description>${post.description}</description>
			<pubDate>${new Date(post.date).toUTCString()}</pubDate>
		</item>
	`).join('\n')}
</channel>
</rss>`;

```

where posts are the data from `static/data/blogs-list.json`.

If it helps - you can look at https://github.com/sveltejs/v2.svelte.dev/blob/b21e7b90ad7f2d62556eba660314e7238a22ce4a/src/routes/blog/rss.xml.js for reference

**Comment by PuruVJ** [comment]
Hi. Thanks for raising this issue. I'm currently working on the 3rd iteration of this site(`puruvjdev3`, its on my github), and I have a lot of new features to add to it, RSS feed and newsletter being one of them.

This repo will be archived and deprecated.

Feel free to clone it and use for your own site. It should still work pretty well.

**Comment by nirtamir2** [comment]
Thanks for letting me know.
Looking forward to it 🙂
